### PR TITLE
deps: revert to using commons-text 1.10.0

### LINKED ISSUE #2686: SpotBugs 4.8.1 fails parsing filter files in Spring Boot projects with NoSuchMethodError: Range.of(Comparable, Comparable)
SpotBugs 4.8.1 fails to parse filter files in projects with Spring Boot which worked with SpotBugs 4.8.0.

Minimal reproducer: https://github.com/josephearl/spotbugs-spring-boot-filter-repro

Error:

```shell
> Task :spotbugsMain FAILED
Exception in thread "main" java.lang.NoSuchMethodError: 'org.apache.commons.lang3.Range org.apache.commons.lang3.Range.of(java.lang.Comparable, java.lang.Comparable)'
        at org.apache.commons.text.translate.NumericEntityEscaper.<init>(NumericEntityEscaper.java:97)
        at org.apache.commons.text.translate.NumericEntityEscaper.between(NumericEntityEscaper.java:59)
        at org.apache.commons.text.StringEscapeUtils.<clinit>(StringEscapeUtils.java:271)
        at edu.umd.cs.findbugs.util.Strings.unescapeXml(Strings.java:295)
        at edu.umd.cs.findbugs.SAXBugCollectionHandler.getRequiredAttribute(SAXBugCollectionHandler.java:804)
        at edu.umd.cs.findbugs.SAXBugCollectionHandler.parseMatcher(SAXBugCollectionHandler.java:452)
        at edu.umd.cs.findbugs.SAXBugCollectionHandler.startElement(SAXBugCollectionHandler.java:340)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1387)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
        at edu.umd.cs.findbugs.filter.Filter.parse(Filter.java:234)
        at edu.umd.cs.findbugs.filter.Filter.parse(Filter.java:208)
        at edu.umd.cs.findbugs.filter.Filter.<init>(Filter.java:133)
        at edu.umd.cs.findbugs.FindBugs.configureFilter(FindBugs.java:471)
        at edu.umd.cs.findbugs.FindBugs2.addFilter(FindBugs2.java:404)
        at edu.umd.cs.findbugs.FindBugs2.configureFilters(FindBugs2.java:551)
        at edu.umd.cs.findbugs.FindBugs2.setUserPreferences(FindBugs2.java:505)
        at edu.umd.cs.findbugs.TextUICommandLine.configureEngine(TextUICommandLine.java:723)
        at edu.umd.cs.findbugs.FindBugs.processCommandLine(FindBugs.java:359)
        at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1221)
```

Expected: SpotBugs 4.8.1 can parse filter files in projects with Spring Boot as 4.8.0 was able to

### PR DESCRIPTION
**Pull request by gtoison**
Upgrading to 1.11.0 caused a version conflict on commons-lang3 which is:
- a direct dependency
- a transitive dependency of commons-text
- a transitive dependency of BCEL

On a Spring/Gradle project the later wins:

     +--- org.apache.bcel:bcel:6.6.1
     |    \--- org.apache.commons:commons-lang3:3.12.0

Revert to commons-text:1.10.0 which is compatible with commons-lang3:3.12.0

Fixes #2686

### CODE REVIEW

**Review by ThrawnCA — APPROVED** [review]

**Comment by JuditKnoll** [comment]
This PR simply reverts https://github.com/spotbugs/spotbugs/pull/2668. Just leaving this here for future reference.

**Review by JuditKnoll — APPROVED** [review]

**Review by ThrawnCA — APPROVED** [review]

**Review by ThrawnCA — APPROVED** [review]

**Review by ThrawnCA — APPROVED** [review]

**Comment by hazendaz** [comment]
@gtoison Can you fix merge conflict?  Then lets just merge this and assume prepare to get next release out here maybe over the weekend unless there are other big items pending.  We can move back up afterwards.

Note: I still think its how user configured their builds as it seems classloaders are mixed up.  But regardless spring boot 3.1.6 would still have the issue and spring boot 3.2.0 would be fixed.  Spring boot 2.7.18 would also still have issue and its no longer free releases at this point as of today.  So we will likely have to revisit it again but we can punt the issue for now and merge this.

**Comment by gtoison** [comment]
I haved merged in the latest changes.
I agree this is not ideal, but at the same time there was not solid reason to upgrade commons-text right now.

**Comment by DamnedElric** [comment]
Wait what? Am I reading this right? You downgraded commons-text because it caused an issue with a transitive dependency in anothe project. But this now causes issues in other projects which do use a newer commons-lang3 (or commons-text) version.

**Comment by gtoison** [comment]
> But this now causes issues in other projects which do use a newer commons-lang3 (or commons-text) version.

What do you mean? What issues are you referring to?

**Comment by hazendaz** [comment]
This is no longer an issue, everything is upgraded.  now.  The PR was not raised back to commons text due to it being blocked.  I'm unblocking it now and will merge so it will be in next release.

**Comment by hazendaz** [comment]
For reference, when we do these kinds of things, we should review later here https://github.com/spotbugs/spotbugs/issues/2222 and make sure we tell renovate to go ahead and raise again.  At this point bcel is on latest all so the original need is no longer valid.
