### PR TITLE
Fix compilation error introduced in 0828aed

### PR DESCRIPTION
**Pull request by iloveeclipse**
See https://github.com/spotbugs/spotbugs/pull/3490

### CODE REVIEW

**Comment by gtoison** [comment]
Sorry about that and thank you for the fix. This looks good to me

**Comment by iloveeclipse** [comment]
> Sorry about that and thank you for the fix. This looks good to me

I just wonder why github actions were all green?
